- name: change route53
  route53:
    state: present
    zone: wread.com
    record: www.wread.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: "d0ec9cb9-a92a-4acf-8954-380fee9770b0
